services:
  - type: web
    name: degenrep-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: DATABASE_URL
        value: postgresql://degencred_bot_user:y3GZTCEIuSK5JtIHlFTDLujYWBjfzUwi@dpg-d1c97kur433s7386em5g-a.oregon-postgres.render.com/degencred_bot
