services:
  - type: web
    name: degenrep-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: DATABASE_URL
        value: your_database_url_here
